version: '3.7'

volumes:
  node_modules:

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: tmh-vk-bot
    container_name: tmh-vk-bot
    restart: unless-stopped
    command: node script.js
    user: node
    image: node:lts-alpine3.14
