version: '3.7'

volumes:
  node_modules:

services:
  node:
    image: tmh-vk-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tmh-vk-bot
    restart: unless-stopped
    command: node script.js
    user: node
